[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m venv --copies venv",
    "./venv/bin/pip install --upgrade pip",
    "./venv/bin/pip install -r requirements.txt",
    "npm install"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "./venv/bin/python server_cached.py"