[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m venv venv",
    "source venv/bin/activate && pip install -r requirements.txt",
    "npm install"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "source venv/bin/activate && python server_cached.py"