[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "nodejs-18_x", "curl", "chromium", "xvfb-run", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --break-system-packages -r requirements.txt",
    "python -m playwright install chromium",
    "npm install"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "python server_cached.py"